/**
 * Generated by fbus codegen(2010-08-01)
 */

#ifndef FCONF_CLIENT_H
#define FCONF_CLIENT_H

#include "fbus_typedef.h"

#include "fconf.h"

FTK_BEGIN_DECLS

FConf* fconf_client_create(void);

FTK_END_DECLS

#endif/*FCONF_CLIENT_H*/
