/**
 * Generated by fbus codegen(2010-08-01)
 */

#include "fconf.h"
#include "fconf_xml.h"
#include "fconf_share.h"
#include "fconf_service.h"

typedef struct _PrivInfo
{
	FConf* impl;
}PrivInfo;

static Ret fconf_marshal_lock(FBusService* thiz, FBusParcel* req_resp)
{

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);


	if((ret = fconf_lock(priv->impl)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
	}

	return ret;
}

static Ret fconf_marshal_unlock(FBusService* thiz, FBusParcel* req_resp)
{

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);


	if((ret = fconf_unlock(priv->impl)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
	}

	return ret;
}

static Ret fconf_marshal_remove(FBusService* thiz, FBusParcel* req_resp)
{
	const char* xpath = {0};

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);

	xpath = fbus_parcel_get_string(req_resp);

	if((ret = fconf_remove(priv->impl, xpath)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
	}

	return ret;
}

static Ret fconf_marshal_set(FBusService* thiz, FBusParcel* req_resp)
{
	const char* xpath = {0};
	const char* value = {0};

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);

	xpath = fbus_parcel_get_string(req_resp);
	value = fbus_parcel_get_string(req_resp);

	if((ret = fconf_set(priv->impl, xpath, value)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
	}

	return ret;
}

static Ret fconf_marshal_get(FBusService* thiz, FBusParcel* req_resp)
{
	const char* xpath = {0};
	char* value = {0};

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);

	xpath = fbus_parcel_get_string(req_resp);

	if((ret = fconf_get(priv->impl, xpath, &value)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
		if(ret == RET_OK)
		{
			fbus_parcel_write_string(req_resp, value);
			FTK_FREE(value);
		}
	}

	return ret;
}

static Ret fconf_marshal_get_child_count(FBusService* thiz, FBusParcel* req_resp)
{
	const char* xpath = {0};
	int count = {0};

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);

	xpath = fbus_parcel_get_string(req_resp);

	if((ret = fconf_get_child_count(priv->impl, xpath, &count)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
		if(ret == RET_OK)
		{
			fbus_parcel_write_int(req_resp, count);
		}
	}

	return ret;
}

static Ret fconf_marshal_get_child(FBusService* thiz, FBusParcel* req_resp)
{
	const char* xpath = {0};
	int index = {0};
	char* child = {0};

	Ret ret = RET_FAIL;
	DECL_PRIV(thiz, priv);
	return_val_if_fail(priv != NULL && priv->impl != NULL && req_resp != NULL, RET_FAIL);

	xpath = fbus_parcel_get_string(req_resp);
	index = fbus_parcel_get_int(req_resp);

	if((ret = fconf_get_child(priv->impl, xpath, index, &child)) == RET_OK)
	{
		fbus_parcel_reset(req_resp);
		fbus_parcel_write_int(req_resp, ret);
		if(ret == RET_OK)
		{
			fbus_parcel_write_string(req_resp, child);
			FTK_FREE(child);
		}
	}

	return ret;
}


static const char* fconf_service_get_name(FBusService* thiz)
{
	return FBUS_SERVICE_FCONF;
}

static Ret fconf_service_on_client_connect(FBusService* thiz, int client_id)
{
	return RET_OK;
}

static Ret fconf_service_on_client_disconnect(FBusService* thiz, int client_id)
{
	return RET_OK;
}

static Ret fconf_service_handle_request(FBusService* thiz, int client_id, FBusParcel* req_resp)
{
	int req_code = fbus_parcel_get_int(req_resp);

	switch(req_code)
	{
		case FCONF_LOCK:
		{
			fconf_marshal_lock(thiz, req_resp);
			break;
		}
		case FCONF_UNLOCK:
		{
			fconf_marshal_unlock(thiz, req_resp);
			break;
		}
		case FCONF_REMOVE:
		{
			fconf_marshal_remove(thiz, req_resp);
			break;
		}
		case FCONF_SET:
		{
			fconf_marshal_set(thiz, req_resp);
			break;
		}
		case FCONF_GET:
		{
			fconf_marshal_get(thiz, req_resp);
			break;
		}
		case FCONF_GET_CHILD_COUNT:
		{
			fconf_marshal_get_child_count(thiz, req_resp);
			break;
		}
		case FCONF_GET_CHILD:
		{
			fconf_marshal_get_child(thiz, req_resp);
			break;
		}
		default:break;
	}
	return RET_OK;
}

static void fconf_service_destroy(FBusService* thiz)
{
	if(thiz != NULL)
	{
		DECL_PRIV(thiz, priv);
		fconf_destroy(priv->impl);
		FTK_FREE(thiz);
	}
	return;
}

FBusService* fconf_service_create(void)
{
	FBusService* thiz = FTK_ZALLOC(sizeof(FBusService)+sizeof(PrivInfo));
	if(thiz != NULL)
	{
		DECL_PRIV(thiz, priv);
		priv->impl = fconf_xml_create();
		thiz->get_name = fconf_service_get_name;
		thiz->on_client_connect = fconf_service_on_client_connect;
		thiz->on_client_disconnect = fconf_service_on_client_disconnect;
		thiz->handle_request = fconf_service_handle_request;
		thiz->destroy = fconf_service_destroy;
		fbus_service_register(thiz);
	}

	return thiz;
}


