/**
 * Generated by fbus codegen(2010-08-01)
 */

#ifndef FCONF_SHARE_H
#define FCONF_SHARE_H

#include "fbus_typedef.h"

FTK_BEGIN_DECLS

typedef enum _FCONF_REQ
{	FCONF_LOCK,
	FCONF_UNLOCK,
	FCONF_REMOVE,
	FCONF_SET,
	FCONF_GET,
	FCONF_GET_CHILD_COUNT,
	FCONF_GET_CHILD,
	FCONF_REQ_NR
}FCONF_REQ;

#define FBUS_SERVICE_FCONF "fbus.service.fconf"

FTK_END_DECLS

#endif/*FCONF_SHARE_H*/
