/**
 * Generated by fbus codegen(2010-08-01)
 */

#ifndef FCONF_SERVICE_H
#define FCONF_SERVICE_H

#include "fbus_service.h"

FTK_BEGIN_DECLS

FBusService* fconf_service_create(void);

FTK_END_DECLS

#endif/*FCONF_SERVICE_H*/
