Import('env')
Import('rtconfig')
Import('RTT_ROOT')
Import('projects')

ftk_app_src	= Split("""
../../demos/demo_check_button.c
""")

ftk_src = Split("""
../../ftk_main_loop_select.c
../../fontdata.c
../../ftk.c
../../ftk_allocator.c
../../ftk_allocator_default.c
../../ftk_allocator_profile.c
../../ftk_animator_alpha.c
../../ftk_animator_expand.c
../../ftk_animator_zoom.c
../../ftk_app_window.c
../../ftk_bitmap.c
../../ftk_bitmap_factory.c
../../ftk_button.c
../../ftk_canvas.c
../../ftk_check_button.c
../../ftk_clipboard.c
../../ftk_combo_box.c
../../ftk_config.c
../../ftk_dialog.c
../../ftk_display.c
../../ftk_display_mem.c
../../ftk_display_rotate.c
../../ftk_entry.c
../../ftk_expr.c
../../ftk_font.c
../../ftk_font_default.c
../../ftk_gesture.c
../../ftk_globals.c
../../ftk_icon_cache.c
../../ftk_icon_view.c
../../ftk_image.c
../../ftk_image_bmp_decoder.c
../../ftk_image_png_decoder.c
../../ftk_input_method_manager.c
../../ftk_input_method_preeditor.c
../../ftk_input_method_preeditor_default.c
../../ftk_label.c
../../ftk_list_model_default.c
../../ftk_list_render_default.c
../../ftk_list_view.c
../../ftk_log.c
../../ftk_main_loop.c
../../ftk_menu_item.c
../../ftk_menu_panel.c
../../ftk_message_box.c
../../ftk_painter.c
../../ftk_path.c
../../ftk_popup_menu.c
../../ftk_progress_bar.c
../../ftk_radio_group.c
../../ftk_scroll_bar.c
../../ftk_sources_manager.c
../../ftk_source_idle.c
../../ftk_source_primary.c
../../ftk_source_timer.c
../../ftk_sprite.c
../../ftk_status_item.c
../../ftk_status_panel.c
../../ftk_tab.c
../../ftk_text_buffer.c
../../ftk_text_layout_normal.c
../../ftk_text_view.c
../../ftk_theme.c
../../ftk_translator.c
../../ftk_util.c
../../ftk_wait_box.c
../../ftk_widget.c
../../ftk_window.c
../../ftk_wnd_manager.c
../../ftk_wnd_manager_default.c
../../ftk_xml_parser.c
../../ftk_xul.c
""")

im_src = Split("""
../../im/ftk_input_method_py.c
../../im/ftk_input_method_util.c
../../im/ftk_lookup_table.c
""")

linebreak_src = Split("""
../../linebreak/linebreak.c
../../linebreak/linebreakdata.c
../../linebreak/linebreakdef.c
""")

rtthread_port_src = Split("""
./ftk_mmap_rtthread.c
./ftk_pipe_rtthread.c
./ftk_rtthread.c
./ftk_select_rtthread.c
../../backend/rt-thread/ftk_backend_rtthread.c
../../backend/rt-thread/ftk_display_rtthread.c
../../backend/rt-thread/ftk_source_touch.c
""")

zlib_src = Split("""
./libz/adler32.c
./libz/compress.c
./libz/crc32.c
./libz/deflate.c
./libz/gzio.c
./libz/infback.c
./libz/inffast.c
./libz/inflate.c 
./libz/inftrees.c 
./libz/trees.c 
./libz/uncompr.c 
./libz/zutil.c
""")

pnglib_src = Split("""
./libpng/png.c 
./libpng/pngerror.c 
./libpng/pnggccrd.c 
./libpng/pngget.c 
./libpng/pngmem.c 
./libpng/pngpread.c 
./libpng/pngread.c 
./libpng/pngrio.c 
./libpng/pngrtran.c 
./libpng/pngrutil.c 
./libpng/pngset.c 
./libpng/pngtrans.c 
./libpng/pngvcrd.c 
./libpng/pngwio.c 
./libpng/pngwrite.c 
./libpng/pngwtran.c
./libpng/pngwutil.c
""")

# The set of source files associated with this SConscript file.
src_local = ftk_src	+ im_src + linebreak_src + rtthread_port_src + zlib_src	+ pnglib_src + ftk_app_src

path = [RTT_ROOT + '/components/external/ftk/src',
	RTT_ROOT + '/components/external/ftk/src/im', 
	RTT_ROOT + '/components/external/ftk/src/os/rt-thread',
	RTT_ROOT + '/components/external/ftk/src/linebreak',
	RTT_ROOT + '/components/external/ftk/src/os/rt-thread/libz', 
	RTT_ROOT + '/components/external/ftk/src/os/rt-thread/libpng',
	RTT_ROOT + '/components/external/ftk/src/backend/rt-thread' ]

# group definitions
group = {}
group['name'] = 'FTK'
group['src'] = File(src_local)
group['CCFLAGS'] = ' -DRT_THREAD'
group['CPPPATH'] = path
group['CPPDEFINES'] = ''
group['LINKFLAGS'] = ''

# add group to project list
projects.append(group)

env.Append(CCFLAGS = group['CCFLAGS'])
env.Append(CPPPATH = group['CPPPATH'])
env.Append(CPPDEFINES = group['CPPDEFINES'])
env.Append(LINKFLAGS = group['LINKFLAGS'])

objs = env.Object(group['src'])

Return('objs')
