#include "ftk_typedef.idl"

struct FtkGlyph
{
	long unused;
};

interface FtkFont
{
	int      ftk_font_height(in FtkFontPtr thiz);
	Ret      ftk_font_lookup (in FtkFontPtr thiz, in unsigned short code, in FtkGlyphPtr glyph);
	void     ftk_font_destroy(in FtkFontPtr thiz);
};

