#include "ftk_widget.idl"

interface FtkPainter : FtkWidget
{
	FtkWidgetPtr ftk_painter_create(inout FtkWidgetPtr parent, in int x, in int y, in int width, in int height);
	Ret ftk_painter_set_paint_listener(inout FtkWidgetPtr thiz, in FtkListenerFunc listener, in voidPtr ctx);
};
