#include "ftk_typedef.idl"

interface FtkListRender
{
	Ret ftk_list_render_init(inout FtkListRenderPtr thiz, in FtkListModelPtr model);
	Ret ftk_list_render_paint(inout FtkListRenderPtr thiz, in FtkCanvasPtr canvas, in int pos, in int x, in int y, in int w, in int h);
	void ftk_list_render_destroy(inout FtkListRenderPtr thiz);
};
