#include "ftk_typedef.idl"

interface FtkPainter
{
	FtkWidget* ftk_painter_create(FtkWidget* parent, int x, int y, int width, int height);
	Ret ftk_painter_set_paint_listener(FtkWidget* thiz, FtkListener listener, void* ctx);
};
