#include "ftk_typedef.idl"

interface FtkDisplay
{
	Ret ftk_display_reg_update_listener(in FtkDisplayPtr thiz, in FtkDisplayOnUpdateFunc on_update, in voidPtr ctx);
	Ret ftk_display_unreg_update_listener(in FtkDisplayPtr thiz, in FtkDisplayOnUpdateFunc on_update, in voidPtr ctx);
	Ret ftk_display_notify(in FtkDisplayPtr thiz, in int before, in FtkBitmapPtr bitmap, in FtkRectPtr rect, in int xoffset, in int yoffset);
	Ret ftk_display_update(in FtkDisplayPtr thiz, in FtkBitmapPtr bitmap, in FtkRectPtr rect, in int xoffset, in int yoffset);
	Ret ftk_display_update_and_notify(in FtkDisplayPtr thiz, in 	FtkBitmapPtr bitmap, in FtkRectPtr rect, in int xoffset, in int yoffset);
	int ftk_display_width(in FtkDisplayPtr thiz);
	int ftk_display_height(in FtkDisplayPtr thiz);
	Ret ftk_display_snap(in FtkDisplayPtr thiz, in size_t x, in size_t y, in FtkBitmapPtr bitmap);
};
