#include "ftk_typedef.idl"

interface FtkSourceTimer
{
	FtkSourcePtr ftk_source_timer_create(in int interval, in FtkTimer action, in voidPtr user_data);
	Ret ftk_source_timer_reset(inout FtkSourcePtr thiz);
};
