#include "ftk_typedef.idl"

interface FtkCanvas
{
	FtkCanvasPtr ftk_canvas_create(in int w, in int h, in FtkColor clear_color);

	Ret ftk_canvas_reset_gc(in FtkCanvasPtr thiz, in FtkGcPtr gc);
	Ret ftk_canvas_set_gc(in FtkCanvasPtr thiz, in FtkGcPtr gc);

	Ret ftk_canvas_draw_vline(in FtkCanvasPtr thiz, in int x, in int y, in int h);
	Ret ftk_canvas_draw_hline(in FtkCanvasPtr thiz, in int x, in int y, in int w);
	Ret ftk_canvas_draw_rect(in FtkCanvasPtr thiz, in int x, in int y, in int w, in int h, in int fill);
	Ret ftk_canvas_draw_round_rect(in FtkCanvasPtr thiz, in int x, in int y, in int w, in int h, in int fill);
	Ret ftk_canvas_draw_string(in FtkCanvasPtr thiz, in int x, in int y, in CStrPtr str, in int len);
	Ret ftk_canvas_draw_string_ex(in FtkCanvasPtr thiz, in int x, in int y, in CStrPtr str, in int len, in int vcenter);

	int ftk_canvas_font_height(in FtkCanvasPtr thiz);
	int ftk_canvas_get_extent(in FtkCanvasPtr thiz, in CStrPtr str, in int len);
	int ftk_canvas_get_char_extent(in FtkCanvasPtr thiz, in unsigned short unicode);

	Ret ftk_canvas_draw_bitmap(in FtkCanvasPtr thiz, in FtkBitmapPtr bitmap, in int x, in int y, in int w, in int h, in int xoffset, in int yoffset);
	Ret ftk_canvas_draw_bg_image(in FtkCanvasPtr canvas, in FtkBitmapPtr bitmap, in FtkBgStyle style, in int x, in int y, in int w, in int h);

	/*the difference between draw and set is: set operation ignore the alpha channel.*/
	Ret ftk_canvas_set_bitmap(in FtkCanvasPtr thiz, in FtkBitmapPtr bitmap, in int x, in int y, in int w, in int h, in int xoffset, in int yoffset);
	Ret ftk_canvas_set_bg_image(in FtkCanvasPtr canvas, in FtkBitmapPtr bitmap, in FtkBgStyle style, in int x, in int y, in int w, in int h);

	FtkColorPtr ftk_canvas_get_pixel(in FtkCanvasPtr thiz, in int x, in int y);
	Ret ftk_canvas_put_pixel(in FtkCanvasPtr thiz, in int x, in int y, in FtkColor val);

	FtkBitmapPtr ftk_canvas_bitmap(in FtkCanvasPtr thiz);
	void ftk_canvas_destroy(in FtkCanvasPtr thiz);
};

