#include "ftk_typedef.idl"

interface FtkMainLoop
{
	FtkMainLoopPtr ftk_main_loop_create(inout FtkSourcesManagerPtr sources_manager);
	Ret  ftk_main_loop_run(inout FtkMainLoopPtr thiz);
	Ret  ftk_main_loop_quit(inout FtkMainLoopPtr thiz);
	Ret  ftk_main_loop_add_source(inout FtkMainLoopPtr thiz, in FtkSourcePtr source);
	Ret  ftk_main_loop_remove_source(inout FtkMainLoopPtr thiz, in FtkSourcePtr source);
	void ftk_main_loop_destroy(inout FtkMainLoopPtr thiz);
};
