#include "ftk_widget.idl"

interface FtkWaitBox : FtkWidget
{
	FtkWidgetPtr ftk_wait_box_create(in FtkWidgetPtr parent, in int x, in int y);
	Ret ftk_wait_box_start_waiting(in FtkWidgetPtr thiz);
	Ret ftk_wait_box_stop_waiting(in FtkWidgetPtr thiz);
};
