#include "ftk_typedef.idl"

interface FtkTheme
{
	FtkThemePtr  ftk_theme_create(in int init_default);
	Ret        ftk_theme_parse_file(inout FtkThemePtr thiz, in CStrPtr filename);
	Ret        ftk_theme_parse_data(inout FtkThemePtr thiz, in CStrPtr data, in size_t length);
	FtkBitmapPtr ftk_theme_load_image(inout FtkThemePtr thiz, in CStrPtr filename);
	FtkBitmapPtr ftk_theme_get_bg(inout FtkThemePtr thiz, in FtkWidgetType type, in FtkWidgetState state);
	FtkColor   ftk_theme_get_bg_color(inout FtkThemePtr thiz, in FtkWidgetType type, in FtkWidgetState state);
	FtkColor   ftk_theme_get_fg_color(inout FtkThemePtr thiz, in FtkWidgetType type, in FtkWidgetState state);
	FtkColor   ftk_theme_get_border_color(inout FtkThemePtr thiz, in FtkWidgetType type, in FtkWidgetState state);
	void       ftk_theme_destroy(inout FtkThemePtr thiz);
};

