#include "ftk_widget.idl"

interface FtkMenuPanel : FtkWidget
{
	FtkWidgetPtr ftk_menu_panel_create();
	Ret ftk_menu_panel_relayout(inout FtkWidgetPtr thiz);
	Ret ftk_menu_panel_add(inout FtkWidgetPtr thiz, in FtkWidgetPtr item);
	Ret ftk_menu_panel_remove(inout FtkWidgetPtr thiz, in FtkWidgetPtr item);
};

