#include "ftk_widget.idl"

interface FtkMenuItem : FtkWidget
{
	FtkWidgetPtr ftk_menu_item_create(inout FtkWidgetPtr parent);
	Ret ftk_menu_item_set_clicked_listener(inout FtkWidgetPtr thiz, in FtkListenerFunc listener, in voidPtr ctx);
};
