#include "ftk_typedef.idl"

interface FtkBitmap
{
	FtkBitmapPtr ftk_bitmap_create(in int w, in int h, in FtkColor clear_color);
	int          ftk_bitmap_width(inout FtkBitmapPtr thiz);
	int          ftk_bitmap_height(inout FtkBitmapPtr thiz);
	FtkColorPtr  ftk_bitmap_bits(inout FtkBitmapPtr thiz);
	void         ftk_bitmap_ref(inout FtkBitmapPtr thiz);
	void         ftk_bitmap_unref(inout FtkBitmapPtr thiz);
};
