#include "ftk_typedef.idl"

interface FtkRadioGroup
{
	FtkWidgetPtr ftk_radio_group_create(inout FtkWidgetPtr parent, in int x, in int y, in int width, in int height);
	Ret  ftk_radio_group_set_checked(inout FtkWidgetPtr thiz, in FtkWidgetPtr radio);
};

