#include "ftk_widget.idl"

interface FtkMenuItem : FtkWidget
{
	FtkWidgetPtr ftk_menu_item_create(in FtkWidgetPtr parent);
	Ret ftk_menu_item_set_clicked_listener(in FtkWidgetPtr thiz, in FtkListenerFunc listener, in voidPtr ctx);
};
