#include "ftk_typedef.idl"

interface FtkMessageBox
{
	int ftk_tips(in CStrPtr text);
	int ftk_warning(in CStrPtr title, in CStrPtr text, in StrArray buttons);
	int ftk_question(in CStrPtr title, in CStrPtr text, in StrArray buttons);
	int ftk_infomation(in CStrPtr title, in CStrPtr text, in StrArray buttons);
};

