/*This file is generated by luagen.*/
#include "lua_ftk_entry.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkEntry");
}

static int lua_ftk_entry_create(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkEntry* retv;
	FtkWidget* parent;
	int x;
	int y;
	int width;
	int height;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err) && tolua_isnumber(tolua_S, 4, 0, &err) && tolua_isnumber(tolua_S, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	parent = tolua_tousertype(tolua_S, 1, 0);
	x = tolua_tonumber(tolua_S, 2, 0);
	y = tolua_tonumber(tolua_S, 3, 0);
	width = tolua_tonumber(tolua_S, 4, 0);
	height = tolua_tonumber(tolua_S, 5, 0);
	retv = ftk_entry_create(parent, x, y, width, height);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkEntry");

	return 1;
}

static int lua_ftk_entry_get_text(lua_State* tolua_S)
{
	tolua_Error err = {0};
	char* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_entry_get_text(thiz);
	tolua_pushstring(tolua_S, (char*)retv);

	return 1;
}

static int lua_ftk_entry_set_text(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	char* text;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isstring(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	text = tolua_tostring(tolua_S, 2, 0);
	retv = ftk_entry_set_text(thiz, text);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_entry_set_input_method(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int index;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	index = tolua_tonumber(tolua_S, 2, 0);
	retv = ftk_entry_set_input_method(thiz, index);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_entry_insert_text(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int pos;
	char* text;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isstring(tolua_S, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	pos = tolua_tonumber(tolua_S, 2, 0);
	text = tolua_tostring(tolua_S, 3, 0);
	retv = ftk_entry_insert_text(thiz, pos, text);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

int tolua_ftk_entry_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkEntry", "FtkEntry", "FtkWidget", NULL);
	tolua_beginmodule(tolua_S, "FtkEntry");
	tolua_function(tolua_S, "Create", lua_ftk_entry_create);
	tolua_function(tolua_S, "GetText", lua_ftk_entry_get_text);
	tolua_function(tolua_S, "SetText", lua_ftk_entry_set_text);
	tolua_function(tolua_S, "SetInputMethod", lua_ftk_entry_set_input_method);
	tolua_function(tolua_S, "InsertText", lua_ftk_entry_insert_text);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
