/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_animator.h"

#ifndef LUA_FtkAnimator_H
#define LUA_FtkAnimator_H

int tolua_ftk_animator_init(lua_State* L);

#endif/*LUA_FtkAnimator_H*/

