/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_sources_manager.h"

#ifndef LUA_FtkSourcesManager_H
#define LUA_FtkSourcesManager_H

int tolua_ftk_sources_manager_init(lua_State* L);

#endif/*LUA_FtkSourcesManager_H*/

