/*This file is generated by luagen.*/
#include "lua_ftk_window.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkWindow");
}

static int lua_ftk_window_set_focus(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* focus_widget;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	focus_widget = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_window_set_focus(thiz, focus_widget);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_get_focus(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_window_get_focus(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_window_grab(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* grab_widget;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	grab_widget = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_window_grab(thiz, grab_widget);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_ungrab(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkWidget* grab_widget;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	grab_widget = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_window_ungrab(thiz, grab_widget);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_paint_forcely(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_window_paint_forcely(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_update(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkRect* rect;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkRect", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	rect = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_window_update(thiz, rect);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_is_fullscreen(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_window_is_fullscreen(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_set_fullscreen(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int fullscreen;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	fullscreen = tolua_tonumber(tolua_S, 2, 0);
	retv = ftk_window_set_fullscreen(thiz, fullscreen);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_invalidate(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkRect* rect;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkRect", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	rect = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_window_invalidate(thiz, rect);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_set_background_with_alpha(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkBitmap* bitmap;
	FtkColor bg;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkBitmap", 0, &err) && tolua_isusertype(tolua_S, 3, "FtkColor", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	bitmap = tolua_tousertype(tolua_S, 2, 0);
	bg = *(FtkColor*)tolua_tousertype(tolua_S, 3, 0);
	retv = ftk_window_set_background_with_alpha(thiz, bitmap, bg);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_enable_update(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_window_enable_update(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_window_disable_update(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_window_disable_update(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

int tolua_ftk_window_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkWindow", "FtkWindow", "FtkWidget", NULL);
	tolua_beginmodule(tolua_S, "FtkWindow");
	tolua_function(tolua_S, "SetFocus", lua_ftk_window_set_focus);
	tolua_function(tolua_S, "GetFocus", lua_ftk_window_get_focus);
	tolua_function(tolua_S, "Grab", lua_ftk_window_grab);
	tolua_function(tolua_S, "Ungrab", lua_ftk_window_ungrab);
	tolua_function(tolua_S, "PaintForcely", lua_ftk_window_paint_forcely);
	tolua_function(tolua_S, "Update", lua_ftk_window_update);
	tolua_function(tolua_S, "IsFullscreen", lua_ftk_window_is_fullscreen);
	tolua_function(tolua_S, "SetFullscreen", lua_ftk_window_set_fullscreen);
	tolua_function(tolua_S, "Invalidate", lua_ftk_window_invalidate);
	tolua_function(tolua_S, "SetBackgroundWithAlpha", lua_ftk_window_set_background_with_alpha);
	tolua_function(tolua_S, "EnableUpdate", lua_ftk_window_enable_update);
	tolua_function(tolua_S, "DisableUpdate", lua_ftk_window_disable_update);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
