/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_font_default.h"
#include "lua_ftk_font.h"

#ifndef LUA_FtkFontDefault_H
#define LUA_FtkFontDefault_H

typedef FtkFont FtkFontDefault;
int tolua_ftk_font_default_init(lua_State* L);

#endif/*LUA_FtkFontDefault_H*/

