/*This file is generated by luagen.*/
#include "lua_ftk_widget.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkWidget");
}

static int lua_ftk_widget_init(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int type;
	int id;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	type = tolua_tonumber(tolua_S, 2, 0);
	id = tolua_tonumber(tolua_S, 3, 0);
	ftk_widget_init(thiz, type, id);

	return 1;
}

static int lua_ftk_widget_type(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_type(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_top(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_top(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_left(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_left(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_top_abs(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_top_abs(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_left_abs(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_left_abs(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_top_in_window(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_top_in_window(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_left_in_window(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_left_in_window(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_width(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_width(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_height(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_height(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_is_insensitive(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_is_insensitive(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_is_visible(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_is_visible(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_is_focused(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_is_focused(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_is_active(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_is_active(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_id(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_id(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_update(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_update(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_get_gc(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkGc* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_get_gc(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkGc");

	return 1;
}

static int lua_ftk_widget_canvas(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkCanvas* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_canvas(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkCanvas");

	return 1;
}

static int lua_ftk_widget_has_attr(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int attr;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	attr = tolua_tonumber(tolua_S, 2, 0);
	retv = ftk_widget_has_attr(thiz, attr);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_state(lua_State* tolua_S)
{
	tolua_Error err = {0};
	int retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_state(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_user_data(lua_State* tolua_S)
{
	tolua_Error err = {0};
	void* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_user_data(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "void");

	return 1;
}

static int lua_ftk_widget_get_text(lua_State* tolua_S)
{
	tolua_Error err = {0};
	char* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_get_text(thiz);
	tolua_pushstring(tolua_S, (char*)retv);

	return 1;
}

static int lua_ftk_widget_invalidate(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_invalidate(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_show(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int visible;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	visible = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_show(thiz, visible);

	return 1;
}

static int lua_ftk_widget_show_all(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int visible;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	visible = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_show_all(thiz, visible);

	return 1;
}

static int lua_ftk_widget_set_visible(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int visible;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	visible = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_visible(thiz, visible);

	return 1;
}

static int lua_ftk_widget_move(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int x;
	int y;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	x = tolua_tonumber(tolua_S, 2, 0);
	y = tolua_tonumber(tolua_S, 3, 0);
	ftk_widget_move(thiz, x, y);

	return 1;
}

static int lua_ftk_widget_resize(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int width;
	int height;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	width = tolua_tonumber(tolua_S, 2, 0);
	height = tolua_tonumber(tolua_S, 3, 0);
	ftk_widget_resize(thiz, width, height);

	return 1;
}

static int lua_ftk_widget_move_resize(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int x;
	int y;
	int width;
	int height;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err) && tolua_isnumber(tolua_S, 4, 0, &err) && tolua_isnumber(tolua_S, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	x = tolua_tonumber(tolua_S, 2, 0);
	y = tolua_tonumber(tolua_S, 3, 0);
	width = tolua_tonumber(tolua_S, 4, 0);
	height = tolua_tonumber(tolua_S, 5, 0);
	ftk_widget_move_resize(thiz, x, y, width, height);

	return 1;
}

static int lua_ftk_widget_set_type(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int type;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	type = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_type(thiz, type);

	return 1;
}

static int lua_ftk_widget_set_insensitive(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int insensitive;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	insensitive = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_insensitive(thiz, insensitive);

	return 1;
}

static int lua_ftk_widget_set_focused(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int focused;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	focused = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_focused(thiz, focused);

	return 1;
}

static int lua_ftk_widget_set_active(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int active;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	active = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_active(thiz, active);

	return 1;
}

static int lua_ftk_widget_set_id(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int id;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	id = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_id(thiz, id);

	return 1;
}

static int lua_ftk_widget_set_canvas(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	FtkCanvas* canvas;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkCanvas", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	canvas = tolua_tousertype(tolua_S, 2, 0);
	ftk_widget_set_canvas(thiz, canvas);

	return 1;
}

static int lua_ftk_widget_set_parent(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	FtkWidget* parent;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	parent = tolua_tousertype(tolua_S, 2, 0);
	ftk_widget_set_parent(thiz, parent);

	return 1;
}

static int lua_ftk_widget_append_child(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	FtkWidget* child;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	child = tolua_tousertype(tolua_S, 2, 0);
	ftk_widget_append_child(thiz, child);

	return 1;
}

static int lua_ftk_widget_append_sibling(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	FtkWidget* next;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	next = tolua_tousertype(tolua_S, 2, 0);
	ftk_widget_append_sibling(thiz, next);

	return 1;
}

static int lua_ftk_widget_remove_child(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	FtkWidget* child;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	child = tolua_tousertype(tolua_S, 2, 0);
	ftk_widget_remove_child(thiz, child);

	return 1;
}

static int lua_ftk_widget_set_attr(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int attr;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	attr = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_set_attr(thiz, attr);

	return 1;
}

static int lua_ftk_widget_unset_attr(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int attr;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	attr = tolua_tonumber(tolua_S, 2, 0);
	ftk_widget_unset_attr(thiz, attr);

	return 1;
}

static int lua_ftk_widget_set_user_data(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	char* destroy;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isstring(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	destroy = tolua_tostring(tolua_S, 2, 0);
	ftk_widget_set_user_data(thiz, lua_ftk_destroy_func, destroy);

	return 1;
}

static int lua_ftk_widget_set_gc(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int state;
	FtkGc* gc;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isusertype(tolua_S, 3, "FtkGc", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	state = tolua_tonumber(tolua_S, 2, 0);
	gc = tolua_tousertype(tolua_S, 3, 0);
	ftk_widget_set_gc(thiz, state, gc);

	return 1;
}

static int lua_ftk_widget_reset_gc(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int state;
	FtkGc* gc;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isusertype(tolua_S, 3, "FtkGc", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	state = tolua_tonumber(tolua_S, 2, 0);
	gc = tolua_tousertype(tolua_S, 3, 0);
	ftk_widget_reset_gc(thiz, state, gc);

	return 1;
}

static int lua_ftk_widget_set_text(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	char* text;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isstring(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	text = tolua_tostring(tolua_S, 2, 0);
	ftk_widget_set_text(thiz, text);

	return 1;
}

static int lua_ftk_widget_toplevel(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_toplevel(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_parent(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_parent(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_prev(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_prev(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_next(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_next(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_child(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_child(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_last_child(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_last_child(thiz);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_lookup(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int id;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	id = tolua_tonumber(tolua_S, 2, 0);
	retv = ftk_widget_lookup(thiz, id);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_find_target(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	FtkWidget* thiz;
	int x;
	int y;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	x = tolua_tonumber(tolua_S, 2, 0);
	y = tolua_tonumber(tolua_S, 3, 0);
	retv = ftk_widget_find_target(thiz, x, y);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

static int lua_ftk_widget_paint(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_paint(thiz);

	return 1;
}

static int lua_ftk_widget_destroy(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_destroy(thiz);

	return 1;
}

static int lua_ftk_widget_ref(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_ref(thiz);

	return 1;
}

static int lua_ftk_widget_unref(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_unref(thiz);

	return 1;
}

static int lua_ftk_widget_paint_self(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	retv = ftk_widget_paint_self(thiz);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

static int lua_ftk_widget_ref_self(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_ref_self(thiz);

	return 1;
}

static int lua_ftk_widget_unref_self(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* thiz;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	ftk_widget_unref_self(thiz);

	return 1;
}

static int lua_ftk_widget_event(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	FtkEvent* event;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isusertype(tolua_S, 2, "FtkEvent", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	event = tolua_tousertype(tolua_S, 2, 0);
	retv = ftk_widget_event(thiz, event);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

int tolua_ftk_widget_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkWidget", "FtkWidget", "", NULL);
	tolua_beginmodule(tolua_S, "FtkWidget");
	tolua_function(tolua_S, "Init", lua_ftk_widget_init);
	tolua_function(tolua_S, "Type", lua_ftk_widget_type);
	tolua_function(tolua_S, "Top", lua_ftk_widget_top);
	tolua_function(tolua_S, "Left", lua_ftk_widget_left);
	tolua_function(tolua_S, "TopAbs", lua_ftk_widget_top_abs);
	tolua_function(tolua_S, "LeftAbs", lua_ftk_widget_left_abs);
	tolua_function(tolua_S, "TopInWindow", lua_ftk_widget_top_in_window);
	tolua_function(tolua_S, "LeftInWindow", lua_ftk_widget_left_in_window);
	tolua_function(tolua_S, "Width", lua_ftk_widget_width);
	tolua_function(tolua_S, "Height", lua_ftk_widget_height);
	tolua_function(tolua_S, "IsInsensitive", lua_ftk_widget_is_insensitive);
	tolua_function(tolua_S, "IsVisible", lua_ftk_widget_is_visible);
	tolua_function(tolua_S, "IsFocused", lua_ftk_widget_is_focused);
	tolua_function(tolua_S, "IsActive", lua_ftk_widget_is_active);
	tolua_function(tolua_S, "Id", lua_ftk_widget_id);
	tolua_function(tolua_S, "Update", lua_ftk_widget_update);
	tolua_function(tolua_S, "GetGc", lua_ftk_widget_get_gc);
	tolua_function(tolua_S, "Canvas", lua_ftk_widget_canvas);
	tolua_function(tolua_S, "HasAttr", lua_ftk_widget_has_attr);
	tolua_function(tolua_S, "State", lua_ftk_widget_state);
	tolua_function(tolua_S, "UserData", lua_ftk_widget_user_data);
	tolua_function(tolua_S, "GetText", lua_ftk_widget_get_text);
	tolua_function(tolua_S, "Invalidate", lua_ftk_widget_invalidate);
	tolua_function(tolua_S, "Show", lua_ftk_widget_show);
	tolua_function(tolua_S, "ShowAll", lua_ftk_widget_show_all);
	tolua_function(tolua_S, "SetVisible", lua_ftk_widget_set_visible);
	tolua_function(tolua_S, "Move", lua_ftk_widget_move);
	tolua_function(tolua_S, "Resize", lua_ftk_widget_resize);
	tolua_function(tolua_S, "MoveResize", lua_ftk_widget_move_resize);
	tolua_function(tolua_S, "SetType", lua_ftk_widget_set_type);
	tolua_function(tolua_S, "SetInsensitive", lua_ftk_widget_set_insensitive);
	tolua_function(tolua_S, "SetFocused", lua_ftk_widget_set_focused);
	tolua_function(tolua_S, "SetActive", lua_ftk_widget_set_active);
	tolua_function(tolua_S, "SetId", lua_ftk_widget_set_id);
	tolua_function(tolua_S, "SetCanvas", lua_ftk_widget_set_canvas);
	tolua_function(tolua_S, "SetParent", lua_ftk_widget_set_parent);
	tolua_function(tolua_S, "AppendChild", lua_ftk_widget_append_child);
	tolua_function(tolua_S, "AppendSibling", lua_ftk_widget_append_sibling);
	tolua_function(tolua_S, "RemoveChild", lua_ftk_widget_remove_child);
	tolua_function(tolua_S, "SetAttr", lua_ftk_widget_set_attr);
	tolua_function(tolua_S, "UnsetAttr", lua_ftk_widget_unset_attr);
	tolua_function(tolua_S, "SetUserData", lua_ftk_widget_set_user_data);
	tolua_function(tolua_S, "SetGc", lua_ftk_widget_set_gc);
	tolua_function(tolua_S, "ResetGc", lua_ftk_widget_reset_gc);
	tolua_function(tolua_S, "SetText", lua_ftk_widget_set_text);
	tolua_function(tolua_S, "Toplevel", lua_ftk_widget_toplevel);
	tolua_function(tolua_S, "Parent", lua_ftk_widget_parent);
	tolua_function(tolua_S, "Prev", lua_ftk_widget_prev);
	tolua_function(tolua_S, "Next", lua_ftk_widget_next);
	tolua_function(tolua_S, "Child", lua_ftk_widget_child);
	tolua_function(tolua_S, "LastChild", lua_ftk_widget_last_child);
	tolua_function(tolua_S, "Lookup", lua_ftk_widget_lookup);
	tolua_function(tolua_S, "FindTarget", lua_ftk_widget_find_target);
	tolua_function(tolua_S, "Paint", lua_ftk_widget_paint);
	tolua_function(tolua_S, "Destroy", lua_ftk_widget_destroy);
	tolua_function(tolua_S, "Ref", lua_ftk_widget_ref);
	tolua_function(tolua_S, "Unref", lua_ftk_widget_unref);
	tolua_function(tolua_S, "PaintSelf", lua_ftk_widget_paint_self);
	tolua_function(tolua_S, "RefSelf", lua_ftk_widget_ref_self);
	tolua_function(tolua_S, "UnrefSelf", lua_ftk_widget_unref_self);
	tolua_function(tolua_S, "Event", lua_ftk_widget_event);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
