/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_animator_expand.h"
#include "lua_ftk_animator.h"

#ifndef LUA_FtkAnimatorExpand_H
#define LUA_FtkAnimatorExpand_H

typedef FtkAnimator FtkAnimatorExpand;
int tolua_ftk_animator_expand_init(lua_State* L);

#endif/*LUA_FtkAnimatorExpand_H*/

