/*This file is generated by luagen.*/
#include "lua_ftk_message_box.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkMessageBox");
}

static int lua_ftk_tips(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	char* text;
	int param_ok = tolua_isstring(L, 1, 0, &err);

	return_val_if_fail(param_ok, 0);

	text = (char*)tolua_tostring(L, 1, 0);
	retv = ftk_tips(text);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_warning(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	char* title;
	char* text;
	char** buttons;
	int param_ok = tolua_isstring(L, 1, 0, &err) && tolua_isstring(L, 2, 0, &err) && tolua_istable(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	title = (char*)tolua_tostring(L, 1, 0);
	text = (char*)tolua_tostring(L, 2, 0);
	buttons = tolua_tostrings(L, 3, 0);
	retv = ftk_warning(title, text, buttons);
	tolua_pushnumber(L, (lua_Number)retv);
	free(buttons);

	return 1;
}

static int lua_ftk_question(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	char* title;
	char* text;
	char** buttons;
	int param_ok = tolua_isstring(L, 1, 0, &err) && tolua_isstring(L, 2, 0, &err) && tolua_istable(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	title = (char*)tolua_tostring(L, 1, 0);
	text = (char*)tolua_tostring(L, 2, 0);
	buttons = tolua_tostrings(L, 3, 0);
	retv = ftk_question(title, text, buttons);
	tolua_pushnumber(L, (lua_Number)retv);
	free(buttons);

	return 1;
}

static int lua_ftk_infomation(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	char* title;
	char* text;
	char** buttons;
	int param_ok = tolua_isstring(L, 1, 0, &err) && tolua_isstring(L, 2, 0, &err) && tolua_istable(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	title = (char*)tolua_tostring(L, 1, 0);
	text = (char*)tolua_tostring(L, 2, 0);
	buttons = tolua_tostrings(L, 3, 0);
	retv = ftk_infomation(title, text, buttons);
	tolua_pushnumber(L, (lua_Number)retv);
	free(buttons);

	return 1;
}

int tolua_ftk_message_box_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkMessageBox", "FtkMessageBox", "", NULL);
	tolua_beginmodule(L, "FtkMessageBox");
	tolua_function(L, "", lua_ftk_tips);
	tolua_function(L, "", lua_ftk_warning);
	tolua_function(L, "", lua_ftk_question);
	tolua_function(L, "", lua_ftk_infomation);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
