/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_image_decoder.h"

#ifndef LUA_FtkImageDecoder_H
#define LUA_FtkImageDecoder_H

int tolua_ftk_image_decoder_init(lua_State* L);

#endif/*LUA_FtkImageDecoder_H*/

