/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_font.h"

#ifndef LUA_FtkFont_H
#define LUA_FtkFont_H

int tolua_ftk_font_init(lua_State* L);

#endif/*LUA_FtkFont_H*/

