/*This file is generated by luagen.*/
#include "lua_ftk_app_window.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkAppWindow");
}

static int lua_ftk_app_window_create(lua_State* tolua_S)
{
	FtkAppWindow* retv;
	retv = ftk_app_window_create();
	tolua_pushusertype(tolua_S, (void*)retv, "FtkAppWindow");

	return 1;
}

static int lua_ftk_app_window_set_on_prepare_options_menu(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	char* on_prepare_options_menu;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isstring(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	on_prepare_options_menu = tolua_tostring(tolua_S, 2, 0);
	retv = ftk_app_window_set_on_prepare_options_menu(thiz, lua_ftk_prepare_options_menu_func, on_prepare_options_menu);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

int tolua_ftk_app_window_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkAppWindow", "FtkAppWindow", "FtkWindow", NULL);
	tolua_beginmodule(tolua_S, "FtkAppWindow");
	tolua_function(tolua_S, "Create", lua_ftk_app_window_create);
	tolua_function(tolua_S, "SetOnPrepareOptionsMenu", lua_ftk_app_window_set_on_prepare_options_menu);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
