/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_canvas.h"

#ifndef LUA_FtkCanvas_H
#define LUA_FtkCanvas_H

int tolua_ftk_canvas_init(lua_State* L);

#endif/*LUA_FtkCanvas_H*/

