/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_animator_alpha.h"
#include "lua_ftk_animator.h"

#ifndef LUA_FtkAnimatorAlpha_H
#define LUA_FtkAnimatorAlpha_H

typedef FtkAnimator FtkAnimatorAlpha;
int tolua_ftk_animator_alpha_init(lua_State* L);

#endif/*LUA_FtkAnimatorAlpha_H*/

