/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_message_box.h"

#ifndef LUA_FtkMessageBox_H
#define LUA_FtkMessageBox_H

int tolua_ftk_message_box_init(lua_State* L);

#endif/*LUA_FtkMessageBox_H*/

