/*This file is generated by luagen.*/
#include "lua_ftk_animator.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkAnimator");
}

static int lua_ftk_animator_stop(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkAnimator* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkAnimator", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_animator_stop(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_animator_start(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkAnimator* thiz;
	FtkWidget* win;
	int sync;
	int param_ok = tolua_isusertype(L, 1, "FtkAnimator", 0, &err) && tolua_isusertype(L, 2, "FtkWidget", 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	win = tolua_tousertype(L, 2, 0);
	sync = tolua_tonumber(L, 3, 0);
	retv = ftk_animator_start(thiz, win, sync);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_animator_set_param(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkAnimator* thiz;
	int type;
	int start;
	int end;
	int step;
	int duration;
	int param_ok = tolua_isusertype(L, 1, "FtkAnimator", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	type = tolua_tonumber(L, 2, 0);
	start = tolua_tonumber(L, 3, 0);
	end = tolua_tonumber(L, 4, 0);
	step = tolua_tonumber(L, 5, 0);
	duration = tolua_tonumber(L, 6, 0);
	retv = ftk_animator_set_param(thiz, type, start, end, step, duration);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_animator_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkAnimator* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkAnimator", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_animator_destroy(thiz);

	return 1;
}

int tolua_ftk_animator_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkAnimator", "FtkAnimator", "", NULL);
	tolua_beginmodule(L, "FtkAnimator");
	tolua_function(L, "Stop", lua_ftk_animator_stop);
	tolua_function(L, "Start", lua_ftk_animator_start);
	tolua_function(L, "SetParam", lua_ftk_animator_set_param);
	tolua_function(L, "Destroy", lua_ftk_animator_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
