/*This file is generated by luagen.*/
#include "lua_ftk_xul.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkXul");
}

static int lua_ftk_xul_load(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkWidget* retv;
	char* xml;
	int length;
	int param_ok = tolua_isstring(tolua_S, 1, 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	xml = tolua_tostring(tolua_S, 1, 0);
	length = tolua_tonumber(tolua_S, 2, 0);
	retv = ftk_xul_load(xml, length);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkWidget");

	return 1;
}

int tolua_ftk_xul_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkXul", "FtkXul", "", NULL);
	tolua_beginmodule(tolua_S, "FtkXul");
	tolua_function(tolua_S, "Load", lua_ftk_xul_load);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
