/*This file is generated by luagen.*/
#include "lua_ftk_button.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* tolua_S)
{
	tolua_usertype(tolua_S, "FtkButton");
}

static int lua_ftk_button_create(lua_State* tolua_S)
{
	tolua_Error err = {0};
	FtkButton* retv;
	FtkWidget* parent;
	int x;
	int y;
	int width;
	int height;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isnumber(tolua_S, 2, 0, &err) && tolua_isnumber(tolua_S, 3, 0, &err) && tolua_isnumber(tolua_S, 4, 0, &err) && tolua_isnumber(tolua_S, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	parent = tolua_tousertype(tolua_S, 1, 0);
	x = tolua_tonumber(tolua_S, 2, 0);
	y = tolua_tonumber(tolua_S, 3, 0);
	width = tolua_tonumber(tolua_S, 4, 0);
	height = tolua_tonumber(tolua_S, 5, 0);
	retv = ftk_button_create(parent, x, y, width, height);
	tolua_pushusertype(tolua_S, (void*)retv, "FtkButton");

	return 1;
}

static int lua_ftk_button_set_clicked_listener(lua_State* tolua_S)
{
	tolua_Error err = {0};
	Ret retv;
	FtkWidget* thiz;
	char* listener;
	int param_ok = tolua_isusertype(tolua_S, 1, "FtkWidget", 0, &err) && tolua_isstring(tolua_S, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(tolua_S, 1, 0);
	listener = tolua_tostring(tolua_S, 2, 0);
	retv = ftk_button_set_clicked_listener(thiz, lua_ftk_listener_func, listener);
	tolua_pushnumber(tolua_S, (lua_Number)retv);

	return 1;
}

int tolua_ftk_button_init(lua_State* tolua_S)
{
	tolua_open(tolua_S);
	tolua_reg_types(tolua_S);
	tolua_module(tolua_S, NULL, 0);
	tolua_beginmodule(tolua_S, NULL);
	tolua_cclass(tolua_S,"FtkButton", "FtkButton", "FtkWidget", NULL);
	tolua_beginmodule(tolua_S, "FtkButton");
	tolua_function(tolua_S, "Create", lua_ftk_button_create);
	tolua_function(tolua_S, "SetClickedListener", lua_ftk_button_set_clicked_listener);
	tolua_endmodule(tolua_S);
	tolua_endmodule(tolua_S);

	return 1;
}
