/*This file is generated by luagen.*/
#include "lua_ftk_canvas.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkCanvas");
}

static int lua_ftk_canvas_create(lua_State* L)
{
	tolua_Error err = {0};
	FtkCanvas* retv;
	int w;
	int h;
	FtkColor clear_color;
	int param_ok = tolua_isnumber(L, 1, 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isusertype(L, 3, "FtkColor", 0, &err);

	return_val_if_fail(param_ok, 0);

	w = tolua_tonumber(L, 1, 0);
	h = tolua_tonumber(L, 2, 0);
	clear_color = *(FtkColor*)tolua_tousertype(L, 3, 0);
	retv = ftk_canvas_create(w, h, clear_color);
	tolua_pushusertype(L, (FtkCanvas*)retv, "FtkCanvas");

	return 1;
}

static int lua_ftk_canvas_reset_gc(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	FtkGc* gc;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isusertype(L, 2, "FtkGc", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	gc = tolua_tousertype(L, 2, 0);
	retv = ftk_canvas_reset_gc(thiz, gc);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_set_gc(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	FtkGc* gc;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isusertype(L, 2, "FtkGc", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	gc = tolua_tousertype(L, 2, 0);
	retv = ftk_canvas_set_gc(thiz, gc);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_vline(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	int h;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	h = tolua_tonumber(L, 4, 0);
	retv = ftk_canvas_draw_vline(thiz, x, y, h);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_hline(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	int w;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	w = tolua_tonumber(L, 4, 0);
	retv = ftk_canvas_draw_hline(thiz, x, y, w);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_rect(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	int w;
	int h;
	int fill;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	w = tolua_tonumber(L, 4, 0);
	h = tolua_tonumber(L, 5, 0);
	fill = tolua_tonumber(L, 6, 0);
	retv = ftk_canvas_draw_rect(thiz, x, y, w, h, fill);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_round_rect(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	int w;
	int h;
	int fill;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	w = tolua_tonumber(L, 4, 0);
	h = tolua_tonumber(L, 5, 0);
	fill = tolua_tonumber(L, 6, 0);
	retv = ftk_canvas_draw_round_rect(thiz, x, y, w, h, fill);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_string(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	char* str;
	int len;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isstring(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	str = (char*)tolua_tostring(L, 4, 0);
	len = tolua_tonumber(L, 5, 0);
	retv = ftk_canvas_draw_string(thiz, x, y, str, len);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_string_ex(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	char* str;
	int len;
	int vcenter;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isstring(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	str = (char*)tolua_tostring(L, 4, 0);
	len = tolua_tonumber(L, 5, 0);
	vcenter = tolua_tonumber(L, 6, 0);
	retv = ftk_canvas_draw_string_ex(thiz, x, y, str, len, vcenter);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_font_height(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkCanvas* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_canvas_font_height(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_get_extent(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkCanvas* thiz;
	char* str;
	int len;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isstring(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	str = (char*)tolua_tostring(L, 2, 0);
	len = tolua_tonumber(L, 3, 0);
	retv = ftk_canvas_get_extent(thiz, str, len);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_get_char_extent(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkCanvas* thiz;
	int unicode;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	unicode = tolua_tonumber(L, 2, 0);
	retv = ftk_canvas_get_char_extent(thiz, unicode);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_bitmap(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	FtkBitmap* bitmap;
	int x;
	int y;
	int w;
	int h;
	int xoffset;
	int yoffset;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isusertype(L, 2, "FtkBitmap", 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err) && tolua_isnumber(L, 7, 0, &err) && tolua_isnumber(L, 8, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	bitmap = tolua_tousertype(L, 2, 0);
	x = tolua_tonumber(L, 3, 0);
	y = tolua_tonumber(L, 4, 0);
	w = tolua_tonumber(L, 5, 0);
	h = tolua_tonumber(L, 6, 0);
	xoffset = tolua_tonumber(L, 7, 0);
	yoffset = tolua_tonumber(L, 8, 0);
	retv = ftk_canvas_draw_bitmap(thiz, bitmap, x, y, w, h, xoffset, yoffset);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_draw_bg_image(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* canvas;
	FtkBitmap* bitmap;
	FtkBgStyle style;
	int x;
	int y;
	int w;
	int h;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isusertype(L, 2, "FtkBitmap", 0, &err) && tolua_isusertype(L, 3, "FtkBgStyle", 0, &err) && tolua_isnumber(L, 4, 0, &err) && tolua_isnumber(L, 5, 0, &err) && tolua_isnumber(L, 6, 0, &err) && tolua_isnumber(L, 7, 0, &err);

	return_val_if_fail(param_ok, 0);

	canvas = tolua_tousertype(L, 1, 0);
	bitmap = tolua_tousertype(L, 2, 0);
	style = *(FtkBgStyle*)tolua_tousertype(L, 3, 0);
	x = tolua_tonumber(L, 4, 0);
	y = tolua_tonumber(L, 5, 0);
	w = tolua_tonumber(L, 6, 0);
	h = tolua_tonumber(L, 7, 0);
	retv = ftk_canvas_draw_bg_image(canvas, bitmap, style, x, y, w, h);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_get_pixel(lua_State* L)
{
	tolua_Error err = {0};
	FtkColor* retv;
	FtkCanvas* thiz;
	int x;
	int y;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	retv = ftk_canvas_get_pixel(thiz, x, y);
	tolua_pushusertype(L, (FtkColor*)retv, "FtkColor");

	return 1;
}

static int lua_ftk_canvas_put_pixel(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkCanvas* thiz;
	int x;
	int y;
	FtkColor val;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isnumber(L, 3, 0, &err) && tolua_isusertype(L, 4, "FtkColor", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	x = tolua_tonumber(L, 2, 0);
	y = tolua_tonumber(L, 3, 0);
	val = *(FtkColor*)tolua_tousertype(L, 4, 0);
	retv = ftk_canvas_put_pixel(thiz, x, y, val);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_canvas_bitmap(lua_State* L)
{
	tolua_Error err = {0};
	FtkBitmap* retv;
	FtkCanvas* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_canvas_bitmap(thiz);
	tolua_pushusertype(L, (FtkBitmap*)retv, "FtkBitmap");

	return 1;
}

static int lua_ftk_canvas_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkCanvas* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkCanvas", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_canvas_destroy(thiz);

	return 1;
}

int tolua_ftk_canvas_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkCanvas", "FtkCanvas", "", NULL);
	tolua_beginmodule(L, "FtkCanvas");
	tolua_function(L, "Create", lua_ftk_canvas_create);
	tolua_function(L, "ResetGc", lua_ftk_canvas_reset_gc);
	tolua_function(L, "SetGc", lua_ftk_canvas_set_gc);
	tolua_function(L, "DrawVline", lua_ftk_canvas_draw_vline);
	tolua_function(L, "DrawHline", lua_ftk_canvas_draw_hline);
	tolua_function(L, "DrawRect", lua_ftk_canvas_draw_rect);
	tolua_function(L, "DrawRoundRect", lua_ftk_canvas_draw_round_rect);
	tolua_function(L, "DrawString", lua_ftk_canvas_draw_string);
	tolua_function(L, "DrawStringEx", lua_ftk_canvas_draw_string_ex);
	tolua_function(L, "FontHeight", lua_ftk_canvas_font_height);
	tolua_function(L, "GetExtent", lua_ftk_canvas_get_extent);
	tolua_function(L, "GetCharExtent", lua_ftk_canvas_get_char_extent);
	tolua_function(L, "DrawBitmap", lua_ftk_canvas_draw_bitmap);
	tolua_function(L, "DrawBgImage", lua_ftk_canvas_draw_bg_image);
	tolua_function(L, "GetPixel", lua_ftk_canvas_get_pixel);
	tolua_function(L, "PutPixel", lua_ftk_canvas_put_pixel);
	tolua_function(L, "Bitmap", lua_ftk_canvas_bitmap);
	tolua_function(L, "Destroy", lua_ftk_canvas_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
