/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_font_free_type.h"
#include "lua_ftk_font.h"

#ifndef LUA_FtkFontFreeType_H
#define LUA_FtkFontFreeType_H

typedef FtkFont FtkFontFreeType;
int tolua_ftk_font_free_type_init(lua_State* L);

#endif/*LUA_FtkFontFreeType_H*/

