/*This file is generated by luagen.*/
#include "lua_ftk_font.h"
#include "lua_ftk_callbacks.h"

static void tolua_reg_types (lua_State* L)
{
	tolua_usertype(L, "FtkFont");
}

static int lua_ftk_font_height(lua_State* L)
{
	tolua_Error err = {0};
	int retv;
	FtkFont* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkFont", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	retv = ftk_font_height(thiz);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_font_lookup(lua_State* L)
{
	tolua_Error err = {0};
	Ret retv;
	FtkFont* thiz;
	int code;
	FtkGlyph* glyph;
	int param_ok = tolua_isusertype(L, 1, "FtkFont", 0, &err) && tolua_isnumber(L, 2, 0, &err) && tolua_isusertype(L, 3, "FtkGlyph", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	code = tolua_tonumber(L, 2, 0);
	glyph = tolua_tousertype(L, 3, 0);
	retv = ftk_font_lookup(thiz, code, glyph);
	tolua_pushnumber(L, (lua_Number)retv);

	return 1;
}

static int lua_ftk_font_destroy(lua_State* L)
{
	tolua_Error err = {0};
	FtkFont* thiz;
	int param_ok = tolua_isusertype(L, 1, "FtkFont", 0, &err);

	return_val_if_fail(param_ok, 0);

	thiz = tolua_tousertype(L, 1, 0);
	ftk_font_destroy(thiz);

	return 1;
}

int tolua_ftk_font_init(lua_State* L)
{
	tolua_open(L);
	tolua_reg_types(L);
	tolua_module(L, NULL, 0);
	tolua_beginmodule(L, NULL);
	tolua_cclass(L,"FtkFont", "FtkFont", "", NULL);
	tolua_beginmodule(L, "FtkFont");
	tolua_function(L, "Height", lua_ftk_font_height);
	tolua_function(L, "Lookup", lua_ftk_font_lookup);
	tolua_function(L, "Destroy", lua_ftk_font_destroy);
	tolua_endmodule(L);
	tolua_endmodule(L);


	return 1;
}
