/*This file is generated by luagen.*/
#include "ftk.h"
#include "tolua++.h"
#include "ftk_radio_group.h"
#include "lua_ftk_widget.h"

#ifndef LUA_FtkRadioGroup_H
#define LUA_FtkRadioGroup_H

typedef FtkWidget FtkRadioGroup;
int tolua_ftk_radio_group_init(lua_State* L);

#endif/*LUA_FtkRadioGroup_H*/

